### ISSUE TITLE
有关视频演示失效

### ISSUE THREAD

**Issue by PonyMaY** [liu-mengyang/MOTinAR#1]
您好！首先非常感谢您在这个项目中的付出与成果！
其实您的另一个模型转换的项目我也在查看，但在这个项目中的一些视频指导已经无法访问了呢，希望您能重新提供！
万分感谢！

**Comment by liu-mengyang** [comment]
演示视频并不重要，主要是介绍GUI的使用，后续会将本仓库关于GUI的内容进行删除，我相信你更关注的是本仓库的其他内容。所以我会关闭这个Issue。
